import type { Config } from 'tailwindcss'

export default <Partial<Config>>{
  theme: {
    extend: {
      colors: { offwhite: '#fcfcfc', primary: '#0CBACD' },
      animation: {
        loaderpulse: 'loaderpulse 1.4s ease infinite',
      },
      keyframes: {
        loaderpulse: {
          '0%': { '--tw-gradient-via-position': '0%' },
          '1%': { '--tw-gradient-via-position': '1%' },
          '2%': { '--tw-gradient-via-position': '2%' },
          '3%': { '--tw-gradient-via-position': '3%' },
          '4%': { '--tw-gradient-via-position': '4%' },
          '5%': { '--tw-gradient-via-position': '5%' },
          '6%': { '--tw-gradient-via-position': '6%' },
          '7%': { '--tw-gradient-via-position': '7%' },
          '8%': { '--tw-gradient-via-position': '8%' },
          '9%': { '--tw-gradient-via-position': '9%' },
          '10%': { '--tw-gradient-via-position': '10%' },
          '11%': { '--tw-gradient-via-position': '11%' },
          '12%': { '--tw-gradient-via-position': '12%' },
          '13%': { '--tw-gradient-via-position': '13%' },
          '14%': { '--tw-gradient-via-position': '14%' },
          '15%': { '--tw-gradient-via-position': '15%' },
          '16%': { '--tw-gradient-via-position': '16%' },
          '17%': { '--tw-gradient-via-position': '17%' },
          '18%': { '--tw-gradient-via-position': '18%' },
          '19%': { '--tw-gradient-via-position': '19%' },
          '20%': { '--tw-gradient-via-position': '20%' },
          '21%': { '--tw-gradient-via-position': '21%' },
          '22%': { '--tw-gradient-via-position': '22%' },
          '23%': { '--tw-gradient-via-position': '23%' },
          '24%': { '--tw-gradient-via-position': '24%' },
          '25%': { '--tw-gradient-via-position': '25%' },
          '26%': { '--tw-gradient-via-position': '26%' },
          '27%': { '--tw-gradient-via-position': '27%' },
          '28%': { '--tw-gradient-via-position': '28%' },
          '29%': { '--tw-gradient-via-position': '29%' },
          '30%': { '--tw-gradient-via-position': '30%' },
          '31%': { '--tw-gradient-via-position': '31%' },
          '32%': { '--tw-gradient-via-position': '32%' },
          '33%': { '--tw-gradient-via-position': '33%' },
          '34%': { '--tw-gradient-via-position': '34%' },
          '35%': { '--tw-gradient-via-position': '35%' },
          '36%': { '--tw-gradient-via-position': '36%' },
          '37%': { '--tw-gradient-via-position': '37%' },
          '38%': { '--tw-gradient-via-position': '38%' },
          '39%': { '--tw-gradient-via-position': '39%' },
          '40%': { '--tw-gradient-via-position': '40%' },
          '41%': { '--tw-gradient-via-position': '41%' },
          '42%': { '--tw-gradient-via-position': '42%' },
          '43%': { '--tw-gradient-via-position': '43%' },
          '44%': { '--tw-gradient-via-position': '44%' },
          '45%': { '--tw-gradient-via-position': '45%' },
          '46%': { '--tw-gradient-via-position': '46%' },
          '47%': { '--tw-gradient-via-position': '47%' },
          '48%': { '--tw-gradient-via-position': '48%' },
          '49%': { '--tw-gradient-via-position': '49%' },
          '50%': { '--tw-gradient-via-position': '50%' },
          '51%': { '--tw-gradient-via-position': '51%' },
          '52%': { '--tw-gradient-via-position': '52%' },
          '53%': { '--tw-gradient-via-position': '53%' },
          '54%': { '--tw-gradient-via-position': '54%' },
          '55%': { '--tw-gradient-via-position': '55%' },
          '56%': { '--tw-gradient-via-position': '56%' },
          '57%': { '--tw-gradient-via-position': '57%' },
          '58%': { '--tw-gradient-via-position': '58%' },
          '59%': { '--tw-gradient-via-position': '59%' },
          '60%': { '--tw-gradient-via-position': '60%' },
          '61%': { '--tw-gradient-via-position': '61%' },
          '62%': { '--tw-gradient-via-position': '62%' },
          '63%': { '--tw-gradient-via-position': '63%' },
          '64%': { '--tw-gradient-via-position': '64%' },
          '65%': { '--tw-gradient-via-position': '65%' },
          '66%': { '--tw-gradient-via-position': '66%' },
          '67%': { '--tw-gradient-via-position': '67%' },
          '68%': { '--tw-gradient-via-position': '68%' },
          '69%': { '--tw-gradient-via-position': '69%' },
          '70%': { '--tw-gradient-via-position': '70%' },
          '71%': { '--tw-gradient-via-position': '71%' },
          '72%': { '--tw-gradient-via-position': '72%' },
          '73%': { '--tw-gradient-via-position': '73%' },
          '74%': { '--tw-gradient-via-position': '74%' },
          '75%': { '--tw-gradient-via-position': '75%' },
          '76%': { '--tw-gradient-via-position': '76%' },
          '77%': { '--tw-gradient-via-position': '77%' },
          '78%': { '--tw-gradient-via-position': '78%' },
          '79%': { '--tw-gradient-via-position': '79%' },
          '80%': { '--tw-gradient-via-position': '80%' },
          '81%': { '--tw-gradient-via-position': '81%' },
          '82%': { '--tw-gradient-via-position': '82%' },
          '83%': { '--tw-gradient-via-position': '83%' },
          '84%': { '--tw-gradient-via-position': '84%' },
          '85%': { '--tw-gradient-via-position': '85%' },
          '86%': { '--tw-gradient-via-position': '86%' },
          '87%': { '--tw-gradient-via-position': '87%' },
          '88%': { '--tw-gradient-via-position': '88%' },
          '89%': { '--tw-gradient-via-position': '89%' },
          '90%': { '--tw-gradient-via-position': '90%' },
          '91%': { '--tw-gradient-via-position': '91%' },
          '92%': { '--tw-gradient-via-position': '92%' },
          '93%': { '--tw-gradient-via-position': '93%' },
          '94%': { '--tw-gradient-via-position': '94%' },
          '95%': { '--tw-gradient-via-position': '95%' },
          '96%': { '--tw-gradient-via-position': '96%' },
          '97%': { '--tw-gradient-via-position': '97%' },
          '98%': { '--tw-gradient-via-position': '98%' },
          '99%': { '--tw-gradient-via-position': '99%' },
          '100%': { '--tw-gradient-via-position': '100%' },
        },
      },
    },
  },
  content: [],
  plugins: [],
}
